Samarth Gakhar
(21BCE0898)

In [27]:
import numpy as np
import pandas as pd                                              #Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)
df = pd.DataFrame({
    'Name': ['Max Verstappen', 'Sergio Perez', 'Daniel', 'Lewis Hamilton'],
    'Age': [25, 33, 33, 37],
    'Average Lap Time': [1.37, 1.38, 1.42, 1.45],
    'Team' :['Red Bull Racing','Red Bull Racing','Alpha Tauri','Mercedes']
})

df

             Name  Age  Average Lap Time             Team
0  Max Verstappen   25              1.37  Red Bull Racing
1    Sergio Perez   33              1.38  Red Bull Racing
2          Daniel   33              1.42      Alpha Tauri
3  Lewis Hamilton   37              1.45         Mercedes

In [38]:
new_column = ['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4']
df.columns = new_column
df                                         #Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'

   Random value 1  Random value 2  Random value 3   Random value 4
0  Max Verstappen              25            1.37  Red Bull Racing
1    Sergio Perez              33            1.38  Red Bull Racing
2          Daniel              33            1.42      Alpha Tauri
3  Lewis Hamilton              37            1.45         Mercedes

In [39]:
df.describe()                                                    #Find the descriptive statistics of the 'df' dataframe.

       Random value 2  Random value 3
count        4.000000        4.000000
mean        32.000000        1.405000
std          5.033223        0.036968
min         25.000000        1.370000
25%         31.000000        1.377500
50%         33.000000        1.400000
75%         34.000000        1.427500
max         37.000000        1.450000

In [40]:

df.isnull()                                                #Check for the null values in 'df' and find the data type of the columns

   Random value 1  Random value 2  Random value 3  Random value 4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False

In [47]:
loc_columns = df.loc[:, ['Random value 2', 'Random value 3']]
print( loc_columns)                                                  #using loc

   Random value 2  Random value 3
0              25            1.37
1              33            1.38
2              33            1.42
3              37            1.45

In [46]:
iloc_columns = df.iloc[:, [1, 2]]                                          #using iloc
print(iloc_columns)

   Random value 2  Random value 3
0              25            1.37
1              33            1.38
2              33            1.42
3              37            1.45